// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK4bDBrdjmm__Z7MKnHeSSleD53TMaNhM',
    appId: '1:691384732208:web:2c99e28455603d874cfbf5',
    messagingSenderId: '691384732208',
    projectId: 'manguod',
    authDomain: 'manguod.firebaseapp.com',
    storageBucket: 'manguod.firebasestorage.app',
    measurementId: 'G-QB5QY1RCXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwgEcTGmUcEUbMFNCr4m2NR_RRA38uQTg',
    appId: '1:691384732208:android:1938bb1919fee2c94cfbf5',
    messagingSenderId: '691384732208',
    projectId: 'manguod',
    storageBucket: 'manguod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQaL5J68o1mqp_vyGgD2VD5w_QzbGaR_g',
    appId: '1:691384732208:ios:c44d269be6072e844cfbf5',
    messagingSenderId: '691384732208',
    projectId: 'manguod',
    storageBucket: 'manguod.firebasestorage.app',
    iosBundleId: 'com.example.chickens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQaL5J68o1mqp_vyGgD2VD5w_QzbGaR_g',
    appId: '1:691384732208:ios:c44d269be6072e844cfbf5',
    messagingSenderId: '691384732208',
    projectId: 'manguod',
    storageBucket: 'manguod.firebasestorage.app',
    iosBundleId: 'com.example.chickens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK4bDBrdjmm__Z7MKnHeSSleD53TMaNhM',
    appId: '1:691384732208:web:12402e1ea6ef76594cfbf5',
    messagingSenderId: '691384732208',
    projectId: 'manguod',
    authDomain: 'manguod.firebaseapp.com',
    storageBucket: 'manguod.firebasestorage.app',
    measurementId: 'G-Q3F4VSBYSM',
  );
}
